# ====== Configuration Parameters ======
# Tune these values based on your gameplay and detection needs.
# --------------------------------------

# ────────────────
# Keyboard Mapping
# ────────────────
# Adjust the following keys to match the in-game keybindings for your character.

key:
  aoe_skill: "q"         # Key to trigger AoE skill (e.g., Monk's AoE heal or Mage's AoE attack)
  directional_attack: "w"        # Key to trigger the basic attack skill, like Mage's Magic Claw
  teleport: ""           # Key to trigger Mage's teleport skill (set to "" to disable)
  jump: "space"          # Key for jumping
  add_hp: "1"             # Key to use a health potion.
  add_mp: "2"           # Key to use a mana potion.

# ────────────────
# Buff skill
# ────────────────
buff_skill:
  keys: []                # Buff skill keys, e.g., magical shield, angel blessing
  cooldown: []            # Cooldown time for each skill (in seconds)
  active_duration: 1      # Duration skill is considered active (in seconds)
  action_cooldown: 1      # Delay after using buff skill before taking action (in seconds)

# ────────────────
# Mage Teleport
# ────────────────
# WIP feature
teleport:
  # whether to activate Mage's teleport skill while walking
  is_use_teleport_to_walk: False
  cooldown: 1 # second # Mage's teleport skill cooldown

# ────────────────
# Edge Teleport
# ────────────────
# Mage can use teleport skill if they're too close to edge
edge_teleport:
  enable: True
  trigger_box_width: 20 # pixel
  trigger_box_height: 10 # pixel
  color_code: [255, 127, 127] # (R,G,B)

# ────────────────
# NameTag Recongnition
# ────────────────
nametag:
  mode: "grayscale" # "grayscale", "white_mask"
  # offset from the nametag's top-left corner to the player's center
  offset: [-50, 30] # pixel
  diff_thres: 0.2

  # Nametag template matching threshold.
  # If the matching diff is smaller than <nametag_global_thres>
  # it will only search area near the last frame nametag.
  # If diff is bigger than <nametag_global_thres>, it will search the whole frame
  # and get the best match.
  # If you find the nametag is cached, but the location is incorrect.
  # Disable this feature by setting nametag_global_thres: 0.0
  global_diff_thres: 0.2
  split_width: 30 # pixel, vertically split nametag

# ────────────────
# Camera
# ────────────────
# only use this vertical range of the screen to localize camera on map
camera:
  y_start: 60  # pixel (top)
  y_end: 665   # pixel (bottom)

# ────────────────
# Attack Settings
# ────────────────
directional_attack:
  # magic claw skill attack range relative to player position
  range_x: 350 # pixels (horizontal range)
  range_y: 70  # pixels (vertical range)
  # attack cooldown time in seconds
  cooldown: 0.05  # seconds between attacks
  # character turn delay before attack
  character_turn_delay: 0.02  # seconds to wait for character to turn before attacking

aoe_skill:
  # aoe skill attack range relative to player position
  range_x: 400 # pixels (horizontal range)
  range_y: 170  # pixels (vertical range)

# ────────────────
# Character
# ────────────────
character:
  width: 100 # pixel
  height: 150 # pixel

# ────────────────
# Monster Detection
# ────────────────
monster_detect:
  mode: "contour_only" # "contour_only" "color", "grayscale" "template_free"
  diff_thres: 0.8 # 0.8   # template match similarity threshold
  search_box_margin: 50  # extra margin around attack box for monster search
  contour_blur: 5
  with_enemy_hp_bar: True
  hp_bar_color: [71,204,64] # (B,G,R)

# ────────────────
# Route Following
# ────────────────
route:
  up_drag_duration: 1.0 # hold duration for 'up' key to prevent rope-sticking (in seconds)
  down_drag_duration: 1.0 # seconds
  search_range: 10 # radius to find nearest color route from player center
  color_code:
    "255,0,0": "walk left"
    "0,0,255": "walk right"
    "255,127,0": "jump left"
    "0,255,255": "jump right"
    "127,255,0": "jump down"
    "255,0,255": "jump"
    "127,127,127": "up"
    "255,255,127": "down"
    "0,255,127": "stop"
    "255,255,0": "goal"
    "255,0,127": "teleport up"
    "127,0,255": "teleport down"
    "0,127,0": "teleport left"
    "139,69,19": "teleport right"

# ────────────────
# Watch dog
# ────────────────
watchdog:
  range: 3 # pixel, if player location is smaller than watch_dog_range, consider it doesn't move
  timeout: 10 # seconds, if player doesn't move for 3 second, random perform an action

# ────────────────
# Runes Warning
# ────────────────
rune_warning:
  top_left    : [513, 196]
  bottom_right: [768, 236]
  diff_thres: 0.2

# ────────────────
# Rune Detection
# ────────────────
rune_detect:
  box_width: 120
  box_height: 150
  diff_thres: 0.1

rune_find:
  timeout: 1200 # second
  near_rune_duration: 5 # second

# ────────────────
# Rune mini-game
# ────────────────
rune_solver:
  arrow_box_size: 80 # pixel, 75x75 box
  arrow_box_interval: 170 # pixel width
  arrow_box_coord: [355, 355]
  arrow_box_diff_thres: 0.2

# ────────────────
# Health Moniter
# ────────────────
health_monitor:
  add_hp_ratio: 0.5 # heal when hp is below 50%
  add_mp_ratio: 0.5 # drink potion when mp is below 50%
  # Health monitor cooldowns (to prevent spam)
  add_hp_cooldown: 0.5  # seconds between heals
  add_mp_cooldown: 0.5    # seconds between MP potions
  fps_limit: 20

# ────────────────
# Mini-Map
# ────────────────
minimap:
  player_color: [136, 255, 255] # BGR
  debug_window_upscale: 4 # upscale 4 time for debug route image

# ────────────────
# Patrol Mode
# ────────────────
patrol:
  range: [0.2, 0.8] # 0.0 - 1.0, 0.0 means the left boarder of game window
                    # 1.0 means the right boarder of game window
  turn_point_thres: 10 # 10 frames
  patrol_attack_interval: 2.5 # sec, attack every 2.5 second

# ────────────────
# Route recoder
# ────────────────
route_recoder:
  blob_cooldown: 0.7 # second, can only draw blob for every 0.7 second
  map_padding: 30 # pixel, How width the black margin on map

# ────────────────
# Game Window
# ────────────────
game_window:
  title: "MapleStory Worlds-Artale (繁體中文版)"
  size: [752, 1282]

# game_window_title: 'MapleStory Worlds-Artale (繁體中文版)'

# ────────────────
# System
# ────────────────
# FPS(Frame per Second) limit for main thread
# TODO: Make other thread fps configurable
system:
  fps_limit_main: 10
  fps_limit_keyboard_controller: 30
  fps_limit_window_capturor: 15
  key_debounce_interval: 1
  show_debug_window: True # False, disable debug window to save system resource

