game_window:
  title: "MapleStory Worlds"
  size: [776, 1280]

monster_detect:
  hp_bar_color: [90, 201, 108] # (B,G,R)

minimap:
  player_color: [84, 255, 255] # BGR
  debug_window_upscale: 2 # upscale 4 time for debug route image
